<?xml version="1.0" encoding="utf-8"?><Database Name="WatchShop" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\WatchShop.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="linktosql.Properties.Settings" SettingsPropertyName="WatchShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.watches" Member="watches">
    <Type Name="watch">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="brand" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="price" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>